Enabled liveness and readiness
openMF/ph-ee-bulk-processor pull request #102
Opened 2023-08-23 08:44 UTC by danishjamal104

###

2023-08-23 10:00 UTC, fynmanoj approved these changes

2023-09-01 14:24 UTC, fynmanoj requested changes

2023-09-01 14:24 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/API/implementation/BatchTransactionsController.java
> +		log.info("Headers passed: {}", headers);
use debug logs

2023-09-01 14:24 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/API/implementation/BatchTransactionsController.java
> +        log.info("Header in exchange: {}", exchange.getIn().getHeaders());
use debug logs

2023-09-01 14:24 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java
> +					logger.info("Zeebe variables published: {}", variables);
use debug logs

2023-09-01 14:24 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java
> +                        logger.info("InstitutionId or programId is null");
use debug logs

2023-09-01 15:02 UTC, danishjamal104 commented on src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java
> +					logger.info("Zeebe variables published: {}", variables);
done

2023-09-01 15:02 UTC, danishjamal104 commented on src/main/java/org/mifos/processor/bulk/API/implementation/BatchTransactionsController.java
> +        log.info("Header in exchange: {}", exchange.getIn().getHeaders());
done

2023-09-01 15:02 UTC, danishjamal104 commented on src/main/java/org/mifos/processor/bulk/camel/routes/ProcessorStartRoute.java
> +                        logger.info("InstitutionId or programId is null");
done

2023-09-01 15:15 UTC, fynmanoj approved these changes

2023-09-02 10:02 UTC, merged