[PHEE-586] Convert BD-003 camel routes to Java/Spring
openMF/ph-ee-bulk-processor pull request #150
Opened 2024-02-15 17:16 UTC by shkr7

[PHEE-586 convert BD-003 camel routes to Java/Spring](https://fynarfin.atlassian.net/browse/PHEE-586?atlOrigin=eyJpIjoiZGE4YzU0NDc1OTk4NDZkZTkwOTE0NTNmNWUwZjQ4MzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Followed the PR title naming convention mentioned above.

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Created/updated unit or integration tests for verifying the changes made.

- [ ] Added required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2024-02-21 10:32 UTC, fynmanoj requested changes

2024-02-21 10:32 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/connectors/service/ProcessorStartRouteService.java
> +        json.put("PollingPath", "/batch/Summary/" + exchange.getProperty(BATCH_ID));
can you take this from a config?

2024-02-21 11:20 UTC, shkr7 commented on src/main/java/org/mifos/processor/bulk/connectors/service/ProcessorStartRouteService.java
> +        json.put("PollingPath", "/batch/Summary/" + exchange.getProperty(BATCH_ID));
Sure, will do it in the next revision.

2024-02-22 09:54 UTC, fynmanoj approved these changes

2024-02-22 09:54 UTC, merged