Added filter for logging tenant
openMF/ph-ee-bulk-processor pull request #57
Opened 2023-04-18 12:51 UTC by truthfool

## Description

- Logged tenant in filters
Jira Ticket GOV- 265 : https://mifosforge.jira.com/browse/GOV-265

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-04-18 12:52 UTC, truthfool commented
@fynmanoj @avikganguly01

2023-05-24 11:15 UTC, fynmanoj requested changes

2023-05-24 11:15 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/api/ApiOriginFilter.java
> +        if (tenantVal.isPresent()) {
we remove this condition

2023-06-01 07:14 UTC, fynmanoj approved these changes

2023-06-01 07:14 UTC, merged