Gov 293 X-Signature header integrated while sending callback
openMF/ph-ee-bulk-processor pull request #59
Opened 2023-05-04 11:53 UTC by danishjamal104

## Description

* Integrated JWS with callback scenario.

Inherits from [this](https://github.com/openMF/ph-ee-bulk-processor/pull/58) PR
For more info refer [GOV-293](https://mifosforge.jira.com/browse/GOV-293?atlOrigin=eyJpIjoiOGE5ZThkOGFlMmY5NDlkNWI3NTJlZDU2NzY4YzU2MmUiLCJwIjoiaiJ9).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

[GOV-293]: https://mifosforge.jira.com/browse/GOV-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-16 13:53 UTC, fynmanoj requested changes

2023-05-16 13:53 UTC, fynmanoj commented on ph-ee-bulk-demo-12.csv
move this file to the documentation

2023-05-16 13:53 UTC, fynmanoj commented on src/main/resources/application.yaml
> +    response:
add configuration for call back as well.

2023-05-24 11:33 UTC, danishjamal104 commented on ph-ee-bulk-demo-12.csv
this is send by mistake ill fix this.

2023-05-24 11:33 UTC, danishjamal104 commented on build.gradle
> +    implementation 'org.mifos:ph-ee-connector-common:1.5.0-SNAPSHOT'
what is RC1?

2023-05-24 11:37 UTC, danishjamal104 commented on ph-ee-bulk-demo-12.csv
done

2023-05-24 13:30 UTC, fynmanoj commented on src/main/resources/application.yaml
> +    response:
jws.callback.enabled

2023-05-24 13:42 UTC, merged