Remove duplicate transactions from input CSV
openMF/ph-ee-bulk-processor pull request #63
Opened 2023-05-15 10:58 UTC by arkadasfynarfin

## Description

* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-05-18 04:26 UTC, arkadasfynarfin commented
@fynmanoj Please review this PR.
cc: @avikganguly01

2023-06-05 09:48 UTC, fynmanoj requested changes

2023-06-05 09:54 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java
> +                set.add(payeeDetail);
warning. adding all transactions to a set can cause memory issues. address this in another ticket

2023-06-05 09:55 UTC, fynmanoj requested changes

2023-06-05 09:55 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java
> +        return payeeIdentifierType + payeeIdentifier + amount + currency;
concatenating with null check can cause null pointer issues.

2023-06-05 10:42 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java
> +        return payeeIdentifierType + payeeIdentifier + amount + currency;
String.format("%s%s%s%s",payeeIdentifierType ,payeeIdentifier , amount ,currency)

2023-06-05 10:46 UTC, fynmanoj requested changes

2023-06-05 10:46 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java
> +            if (currentPayeeDetail.equals(nextPayeeDetail)) {
not null safe , this method: fetchPayeeDetail(currentTransaction) can possibly return null ( as the method has a return null )

2023-06-05 10:46 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/OrderingWorker.java
> +        if(Objects.isNull(transaction)){
null check already exist before this call. unless this method is reused, you can remove the redundant code.

2023-06-05 11:00 UTC, merged