Added auto dependency management for spring
openMF/ph-ee-bulk-processor pull request #68
Opened 2023-05-31 06:15 UTC by danishjamal104

2023-05-31 07:15 UTC, danishjamal104 commented
@fynmanoj and @avikganguly01 please review and merge. THanks :)

2023-05-31 11:36 UTC, fynmanoj requested changes

2023-05-31 11:36 UTC, fynmanoj commented on build.gradle
> +    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
lets remove this plug in once the dependency issues are sorted out.

2023-06-01 14:40 UTC, fynmanoj approved these changes

2023-06-02 06:19 UTC, merged