GOV-359: Add batch aggregate worker to bulk processor
openMF/ph-ee-bulk-processor pull request #76
Opened 2023-07-07 11:54 UTC by arkadasfynarfin

2023-07-07 13:25 UTC, arkadasfynarfin commented
@fynmanoj Please review this PR.
CC: @avikganguly01

2023-07-21 06:00 UTC, fynmanoj commented
rebase and resolve conflicts

2023-07-27 09:58 UTC, fynmanoj requested changes

2023-07-27 09:58 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/zeebe/worker/BatchStatusWorker.java
> +            long successRate = calculateSuccessPercentage(batchDTOResponse);
use float for percentage

2023-07-27 09:58 UTC, fynmanoj commented on src/main/resources/application.yaml
> +    batch-aggregate: "/api/v1/batch/"
I would recommend you stick with the camelcase property definitions.

2023-08-23 17:27 UTC, fynmanoj requested changes

2023-08-23 17:27 UTC, fynmanoj commented on demo.csv
> +id,request_id,payment_mode,payer_identifier_type,payer_identifier,payee_identifier_type,payee_identifier,amount,currency,note
remove this file

2023-08-23 17:27 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/API/BatchTransactions.java
> +    String batchTransactions(@RequestHeader(value = "X-CorrelationID") String requestId,
please rebase, This is already added

2023-08-23 17:27 UTC, fynmanoj commented on src/main/java/org/mifos/processor/bulk/config/BudgetAccountConfig.java
> +    public RegisteringInstitutionConfig getByRegisteringInstituteId(String id) {
please rebase

2023-09-26 13:24 UTC, closed without merging