Remove unnecessary merge conflict text from application.yaml
openMF/ph-ee-bulk-processor pull request #88
Opened 2023-08-04 12:29 UTC by arkadasfynarfin

2023-08-04 12:47 UTC, arkadasfynarfin commented
@fynmanoj Please review and merge this PR.

2023-08-04 13:24 UTC, fynmanoj commented
Can you link the is to the same JIRA ticket

2023-08-04 13:26 UTC, fynmanoj requested changes

2023-08-04 13:26 UTC, fynmanoj commented on 1687948148685_demo.csv
Please and .csv file to git ignore so that these wont endup here again.
Also please  check whether these files will be added to file system always and is there a way to clean this up

2023-08-07 09:12 UTC, fynmanoj commented
mention a JIRA ticket number

2023-08-07 09:13 UTC, merged

2023-08-07 10:29 UTC, arkadasfynarfin commented
> mention a JIRA ticket number

@fynmanoj I have linked the PR to the Dhruv's PR which created this issue. There was no JIRA ticket created for this (as per Dhruv).